Configurable remote diarization server timeout
Wordcab/wordcab-transcribe pull request #283
Opened 2023-11-15 20:01 UTC by michalblaha

via `.env` file or environment variable 
based on previous pull request, Modified according to proposals @aleksandr-smechov and @karmi
 
added patch version change

2023-11-15 20:54 UTC, aleksandr-smechov commented on .env
The version can remain the same, as it's a minor change

2023-11-15 21:07 UTC, aleksandr-smechov commented
@michalblaha Left comments, thank you

2023-11-15 21:55 UTC, michalblaha commented on src/wordcab_transcribe/services/asr_service.py
> +        specifictimeout = aiohttp.ClientTimeout(total=int(os.getenv("REMOTE_DIARIZE_SERVER_REQUEST_TIMEOUT_SEC", 300)))
Hi.
1) .env - its there. See https://github.com/Wordcab/wordcab-transcribe/pull/283/files
2) config & Settings class - ok, I'll change it
3) I've tested it on my infrastructure in docker, with `-e "REMOTE_DIARIZE_SERVER_REQUEST_TIMEOUT_SEC=30000"`

2023-11-15 21:57 UTC, michalblaha commented
Thanks, so do I. 
BTW, could you check annoying bug #280 ? thx

2023-11-17 02:12 UTC, aleksandr-smechov requested changes

2023-11-17 02:12 UTC, aleksandr-smechov commented on .env
> +VERSION="0.5.2.1"
No version increment

2023-11-17 02:12 UTC, aleksandr-smechov commented on .env
> +REMOTE_DIARIZE_SERVER_REQUEST_TIMEOUT_SEC=300
Just `REMOTE_DIARIZATION_SERVER_REQUEST_TIMEOUT=300`

to keep things consistent

2023-11-17 02:12 UTC, aleksandr-smechov commented on src/wordcab_transcribe/__init__.py
> +__version__ = "0.5.2.1"
No increment

2023-11-17 02:12 UTC, aleksandr-smechov commented on src/wordcab_transcribe/config.py
> +    remote_diarization_request_timeout=int(os.getenv("REMOTE_DIARIZE_SERVER_REQUEST_TIMEOUT_SEC", 300)),
remote_diarization_request_timeout=getenv("REMOTE_DIARIZATION_SERVER_REQUEST_TIMEOUT", 300),

2023-11-17 02:12 UTC, aleksandr-smechov commented on src/wordcab_transcribe/services/asr_service.py
> +                f"remote diarization server timeout is {settings.remote_diarization_request_timeout}"
`f"Remote diarization server timeout set to {settings.remote_diarization_request_timeout}"`

2023-11-17 02:12 UTC, aleksandr-smechov commented on src/wordcab_transcribe/services/asr_service.py
> +        logger.info(f"settings.remote_diarization_request_timeout={settings.remote_diarization_request_timeout} secs")
Can remove lines 783-785

2024-03-21 19:21 UTC, closed without merging